quadrantChart
    title "贪吃蛇游戏市场竞争分析"
    x-axis "功能简单" --> "功能丰富"
    y-axis "体验一般" --> "体验优秀"
    quadrant-1 "重点发展"
    quadrant-2 "需要推广"
    quadrant-3 "重新评估"
    quadrant-4 "可以改进"
    "经典贪吃蛇": [0.3, 0.4]
    "在线游戏A": [0.6, 0.5]
    "移动端游戏B": [0.4, 0.7]
    "游戏C": [0.8, 0.3]
    "开源项目": [0.5, 0.4]
    "游戏D": [0.7, 0.6]
    "游戏E": [0.9, 0.8]
    "我们的目标产品": [0.7, 0.7]